### ISSUE TITLE
Pages are shown even if I don't have permission

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Products#65] opened 2017-09-29 13:14 UTC
### Steps to reproduce

1. Start Products
2. Start SignIn
3. Go to http://localhost:8080/products/settings

### Expected result

I should see the message that I don't have permission to access the page

### Actual result

I see the page and the message

### Technical information

Version=2.3.1.7334

##### Involved apps' version

- StarcounterApps/Products@cf5719b3415f4225ee48a03b7bd4e4f0153ade80
- StarcounterApps/SignIn@45ed21866d270f96ea605eb9086f6cf4de7e290a
 
### Screenshot
![capture4](https://user-images.githubusercontent.com/19392292/31017463-2f6bc7ee-a4ee-11e7-94c7-59b6f59f59cc.PNG)

**Comment by Mihaiii** [comment] 2018-01-24 17:58
I looked into this.
The settings page doesn't require permission.
What is shown in the screenshot is from SignIn's settings page and that is an effect of mapping.

AFAIK no decision was made to make the settings pages from all running apps only one way (since the context was introduce). I will talk about this at the next team meeting.

Thank you for reporting.
Closing as not a bug and a duplicate of https://github.com/StarcounterApps/Cashier/issues/20.

For more details please also see https://github.com/Starcounter/RebelsLounge/issues/153 .

**Closed by Mihaiii** 2018-01-24 17:58 UTC
Labels: bug
